services:
  selena-translator:
    build: .
    image: selena-translator:latest
    container_name: selena-translator
    ports:
      - "8002:8002"
    volumes:
      - ${HOME}/.local/share/argos-translate/packages:/root/.local/share/argos-translate/packages
      - ./data/helsinki-out:/app/data/helsinki-out
      - ./data/hf-cache:/root/.cache/huggingface
    restart: unless-stopped
